events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name jakubjaskulski.com jakubjaskulski.net;

        # Frontend Angular
        location / {
            proxy_pass http://jjdevhub-angular:80;
            proxy_set_header Host $host;
        }

        # Backend API (Modular Monolith)
        location /api/ {
            proxy_pass http://jjdevhub-content-api:8080; # Zakładając port Twojego .NET
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Jenkins (Dla Twojej wygody pod subdomeną)
        location /jenkins/ {
            proxy_pass http://jjdevhub-jenkins:8080;
        }
    }
}
